### ISSUE TITLE
How to run application

### ISSUE THREAD

**Issue by DineshGuptaa** [SamiurRahmanMukul/Hotel-Room-Booking-System#1]
Please provide guide line  how to execute the project locally. That will be helpful to all.

**Comment by SamiurRahmanMukul** [comment]
@DineshGuptaa I will share shortly locally project set up guideline

**Comment by Sravanthi9990** [comment]
can you please provide guide line..

**Comment by SamiurRahmanMukul** [comment]
Apologies, the guidelines for setting up the app locally are not available at the moment. We will share them with you at a later time.
